# Generated by Django 5.2.9 on 2026-01-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamificationprofile',
            table='gamification_profile',
        ),
    ]
