# Generated by Django 5.2.9 on 2026-01-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_gamificationprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamificationprofile',
            table=None,
        ),
    ]
