# Generated by Django 5.2.9 on 2025-12-08 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('name', models.CharField(max_length=100, verbose_name='배너 이름(내부용)')),
                ('position', models.CharField(choices=[('TOP_GLOBAL', '전체 상단'), ('GAME_TOP', '게임 상단')], max_length=50, verbose_name='배너 위치')),
                ('image_url', models.URLField(max_length=255, verbose_name='이미지 URL')),
                ('link_url', models.URLField(max_length=255, verbose_name='링크 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='노출 시작 시각')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='노출 종료 시각')),
            ],
            options={
                'verbose_name': '배너',
                'verbose_name_plural': '배너',
                'db_table': 'gaimification_banner',
                'ordering': ['-is_active', '-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorldcupTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('name', models.CharField(max_length=50, verbose_name='주제명')),
                ('slug', models.SlugField(unique=True, verbose_name='URL 식별자')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
            ],
            options={
                'verbose_name': '월드컵 주제',
                'verbose_name_plural': '월드컵 주제',
                'db_table': 'gaimification_worldcup_topic',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('title', models.CharField(max_length=100, verbose_name='게임 제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL 경로')),
                ('type', models.CharField(choices=[('WORLD_CUP', '이상형 월드컵'), ('FORTUNE_TEST', '운세 테스트'), ('QUIZ', '퀴즈')], default='WORLD_CUP', max_length=20, verbose_name='게임 타입')),
                ('status', models.CharField(choices=[('DRAFT', '작성중'), ('ACTIVE', '진행중'), ('STOPPED', '중지됨'), ('ARCHIVED', '보관됨')], default='DRAFT', max_length=20, verbose_name='상태')),
                ('is_official', models.BooleanField(default=False, verbose_name='공식 게임 여부')),
                ('visibility', models.CharField(choices=[('PUBLIC', '공개'), ('PRIVATE', '비공개'), ('UNLISTED', '링크 공개')], default='PUBLIC', max_length=20, verbose_name='공개 범위')),
                ('thumbnail_image_url', models.URLField(blank=True, max_length=255, verbose_name='썸네일 URL')),
                ('storage_prefix', models.CharField(help_text='이미지 등이 저장되는 폴더 prefix (예: worldcup/ab12cd/)', max_length=255, verbose_name='스토리지 prefix')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='노출 시작 시각')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='노출 종료 시각')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL, verbose_name='생성 유저')),
                ('parent_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.worldcuptopic', verbose_name='월드컵 주제')),
            ],
            options={
                'verbose_name': '게임',
                'verbose_name_plural': '게임',
                'db_table': 'gaimification_game',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('name', models.CharField(blank=True, help_text='표시용 이름, 비워두면 프론트에서 기본값으로 처리 가능', max_length=100, verbose_name='후보명')),
                ('file_name', models.CharField(help_text='실제 저장된 파일명 (예: 1.jpg, a83fae.png)', max_length=255, verbose_name='파일명')),
                ('source_type', models.CharField(choices=[('USER_UPLOAD', '유저 업로드'), ('OFFICIAL', '공식')], default='USER_UPLOAD', max_length=20, verbose_name='소스 타입')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('is_approved', models.BooleanField(default=True, verbose_name='승인 여부')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='차단 여부')),
                ('report_count', models.IntegerField(default=0, verbose_name='신고 횟수')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.game', verbose_name='게임')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_game_items', to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '게임 아이템',
                'verbose_name_plural': '게임 아이템',
                'db_table': 'gaimification_game_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('session_token', models.CharField(help_text='비로그인 사용자를 위한 랜덤 세션 토큰', max_length=64, verbose_name='세션 토큰')),
                ('source', models.CharField(blank=True, help_text='direct, banner_top, share_kakao 등', max_length=50, verbose_name='유입 경로')),
                ('referer_url', models.URLField(blank=True, max_length=255, verbose_name='Referer URL')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP 주소')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시각')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game', verbose_name='게임')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '게임 세션',
                'verbose_name_plural': '게임 세션',
                'db_table': 'gaimification_game_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_title', models.CharField(max_length=100, verbose_name='결과 제목')),
                ('result_code', models.CharField(blank=True, help_text='내부적으로 사용하는 코드 (예: TYPE_A 등)', max_length=50, verbose_name='결과 코드')),
                ('result_image_url', models.URLField(blank=True, max_length=255, verbose_name='결과 이미지 URL')),
                ('share_url', models.URLField(blank=True, max_length=255, verbose_name='공유 URL')),
                ('result_payload', models.JSONField(blank=True, help_text='점수 breakdown 등 JSON 형태로 저장', null=True, verbose_name='결과 상세 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='games.game', verbose_name='게임')),
                ('winner_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_results', to='games.gameitem', verbose_name='우승 아이템')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='games.gamesession', verbose_name='게임 세션')),
            ],
            options={
                'verbose_name': '게임 결과',
                'verbose_name_plural': '게임 결과',
                'db_table': 'gaimification_game_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameChoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(verbose_name='선택 순서 (0부터 시작)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_logs', to='games.game', verbose_name='게임')),
                ('left_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_choices', to='games.gameitem', verbose_name='왼쪽 아이템')),
                ('right_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_choices', to='games.gameitem', verbose_name='오른쪽 아이템')),
                ('selected_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_choices', to='games.gameitem', verbose_name='선택된 아이템')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='games.gamesession', verbose_name='게임 세션')),
            ],
            options={
                'verbose_name': '게임 선택 로그',
                'verbose_name_plural': '게임 선택 로그',
                'db_table': 'gaimification_game_choice_log',
                'ordering': ['session_id', 'step_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BannerClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='클릭 시각')),
                ('referer_url', models.URLField(blank=True, max_length=255, verbose_name='Referer URL')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP 주소')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='games.banner', verbose_name='배너')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_click_logs', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_click_logs', to='games.game', verbose_name='게임')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_click_logs', to='games.gamesession', verbose_name='게임 세션')),
            ],
            options={
                'verbose_name': '배너 클릭 로그',
                'verbose_name_plural': '배너 클릭 로그',
                'db_table': 'gaimification_banner_click_log',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
