from django.urls import path
from .views import (
    GameListView,
    GameDetailView,
    GameChoiceLogCreateView,
    GameResultCreateView,
    WorldcupPickLogCreateView,
    WorldcupCreateView,
    WorldcupTopicCreateView,
    WorldcupTopicListView,
    MyGameListView,
    WorldcupDraftView,
    AdminGameDeleteView,
    AdminGameListView,
    AdminGameDetailView,
    AdminGameItemUpdateView,
    AdminGameItemCreateView,
    AdminGameItemDeleteView,
    AdminGameUpdateView,
    AdminGameChoiceLogListView,
    AdminGameResultListView,
    AdminWorldcupPickLogListView,
    AdminWorldcupTopicDeleteView,
    AdminWorldcupTopicListView,
    AdminWorldcupTopicUpdateView,
    AdminJsonListView,
    AdminJsonDetailView,
    GameJsonReadView,
)

app_name = 'games'

urlpatterns = [
    path("", GameListView.as_view(), name="list"),
    path("mine/", MyGameListView.as_view(), name="mine"),
    path("<int:game_id>/", GameDetailView.as_view(), name="detail"),
    path("session/", GameChoiceLogCreateView.as_view(), name="session_create"),
    path("worldcup/pick/", WorldcupPickLogCreateView.as_view(), name="worldcup_pick_create"),
    path("worldcup/create/", WorldcupCreateView.as_view(), name="worldcup_create"),
    path("worldcup/draft/", WorldcupDraftView.as_view(), name="worldcup_draft"),
    path("worldcup/topics/", WorldcupTopicListView.as_view(), name="worldcup_topics"),
    path(
        "worldcup/topics/create/",
        WorldcupTopicCreateView.as_view(),
        name="worldcup_topic_create",
    ),
    path("admin/games/", AdminGameListView.as_view(), name="admin_games_list"),
    path("admin/games/update/", AdminGameUpdateView.as_view(), name="admin_games_update"),
    path("admin/games/items/update/", AdminGameItemUpdateView.as_view(), name="admin_games_items_update"),
    path("admin/games/items/create/", AdminGameItemCreateView.as_view(), name="admin_games_items_create"),
    path("admin/games/items/<int:item_id>/delete/", AdminGameItemDeleteView.as_view(), name="admin_games_items_delete"),
    path("admin/games/<int:game_id>/", AdminGameDetailView.as_view(), name="admin_games_detail"),
    path("admin/games/<int:game_id>/delete/", AdminGameDeleteView.as_view(), name="admin_games_delete"),
    path("admin/topics/", AdminWorldcupTopicListView.as_view(), name="admin_topics_list"),
    path("admin/topics/update/", AdminWorldcupTopicUpdateView.as_view(), name="admin_topics_update"),
    path("admin/topics/<int:topic_id>/delete/", AdminWorldcupTopicDeleteView.as_view(), name="admin_topics_delete"),
    path("admin/logs/choices/", AdminGameChoiceLogListView.as_view(), name="admin_logs_choice"),
    path("admin/logs/picks/", AdminWorldcupPickLogListView.as_view(), name="admin_logs_pick"),
    path("admin/results/", AdminGameResultListView.as_view(), name="admin_results_list"),
    path("admin/json/", AdminJsonListView.as_view(), name="admin_json_list"),
    path("admin/json/file/", AdminJsonDetailView.as_view(), name="admin_json_detail"),
    path("json/", GameJsonReadView.as_view(), name="json_read"),
    path("result/", GameResultCreateView.as_view(), name="result_create"),
]
